// GENERATED by packages/core/scripts/gen-abis.mjs — do not edit.
// Source of truth: src/abi/*.json at the repo root (see scripts/extract-abis.mjs).

import { DirectDemocracyVotingNewAbi } from './DirectDemocracyVotingNew';
import { ERC20Abi } from './ERC20';
import { EducationHubNewAbi } from './EducationHubNew';
import { ExecutorAbi } from './Executor';
import { HybridVotingNewAbi } from './HybridVotingNew';
import { ImplementationRegistryAbi } from './ImplementationRegistry';
import { MembershipAuthorityAbi } from './MembershipAuthority';
import { OrgDeployerNewAbi } from './OrgDeployerNew';
import { OrgRegistryAbi } from './OrgRegistry';
import { ParticipationTokenAbi } from './ParticipationToken';
import { PasskeyAccountAbi } from './PasskeyAccount';
import { PasskeyAccountFactoryAbi } from './PasskeyAccountFactory';
import { PaymasterHubAbi } from './PaymasterHub';
import { PaymentManagerAbi } from './PaymentManager';
import { PoaManagerAbi } from './PoaManager';
import { QuickJoinNewAbi } from './QuickJoinNew';
import { TaskManagerNewAbi } from './TaskManagerNew';
import { UniversalAccountRegistryAbi } from './UniversalAccountRegistry';
import { ZkEmailInvitesAbi } from './ZkEmailInvites';
import { AaveGovernanceV2Abi } from './external/AaveGovernanceV2';
import { AaveGovernanceV3Abi } from './external/AaveGovernanceV3';
import { AragonVotingAbi } from './external/AragonVoting';
import { CurveGaugeControllerAbi } from './external/CurveGaugeController';
import { CurveVotingEscrowAbi } from './external/CurveVotingEscrow';
import { GovernorAlphaAbi } from './external/GovernorAlpha';
import { MakerDAOChiefAbi } from './external/MakerDAOChief';
import { OZGovernorAbi } from './external/OZGovernor';
import { SolidlyVotingEscrowAbi } from './external/SolidlyVotingEscrow';

export { DirectDemocracyVotingNewAbi };
export { ERC20Abi };
export { EducationHubNewAbi };
export { ExecutorAbi };
export { HybridVotingNewAbi };
export { ImplementationRegistryAbi };
export { MembershipAuthorityAbi };
export { OrgDeployerNewAbi };
export { OrgRegistryAbi };
export { ParticipationTokenAbi };
export { PasskeyAccountAbi };
export { PasskeyAccountFactoryAbi };
export { PaymasterHubAbi };
export { PaymentManagerAbi };
export { PoaManagerAbi };
export { QuickJoinNewAbi };
export { TaskManagerNewAbi };
export { UniversalAccountRegistryAbi };
export { ZkEmailInvitesAbi };
export { AaveGovernanceV2Abi };
export { AaveGovernanceV3Abi };
export { AragonVotingAbi };
export { CurveGaugeControllerAbi };
export { CurveVotingEscrowAbi };
export { GovernorAlphaAbi };
export { MakerDAOChiefAbi };
export { OZGovernorAbi };
export { SolidlyVotingEscrowAbi };

/** Every first-party POP ABI, keyed by its historical abi/ file base name. */
export const ALL_ABIS: Record<string, readonly unknown[]> = {
  "DirectDemocracyVotingNew": DirectDemocracyVotingNewAbi,
  "ERC20": ERC20Abi,
  "EducationHubNew": EducationHubNewAbi,
  "Executor": ExecutorAbi,
  "HybridVotingNew": HybridVotingNewAbi,
  "ImplementationRegistry": ImplementationRegistryAbi,
  "MembershipAuthority": MembershipAuthorityAbi,
  "OrgDeployerNew": OrgDeployerNewAbi,
  "OrgRegistry": OrgRegistryAbi,
  "ParticipationToken": ParticipationTokenAbi,
  "PasskeyAccount": PasskeyAccountAbi,
  "PasskeyAccountFactory": PasskeyAccountFactoryAbi,
  "PaymasterHub": PaymasterHubAbi,
  "PaymentManager": PaymentManagerAbi,
  "PoaManager": PoaManagerAbi,
  "QuickJoinNew": QuickJoinNewAbi,
  "TaskManagerNew": TaskManagerNewAbi,
  "UniversalAccountRegistry": UniversalAccountRegistryAbi,
  "ZkEmailInvites": ZkEmailInvitesAbi,
};

/** Third-party governance ABIs (probe targets), keyed by file base name. */
export const EXTERNAL_ABIS: Record<string, readonly unknown[]> = {
  "AaveGovernanceV2": AaveGovernanceV2Abi,
  "AaveGovernanceV3": AaveGovernanceV3Abi,
  "AragonVoting": AragonVotingAbi,
  "CurveGaugeController": CurveGaugeControllerAbi,
  "CurveVotingEscrow": CurveVotingEscrowAbi,
  "GovernorAlpha": GovernorAlphaAbi,
  "MakerDAOChief": MakerDAOChiefAbi,
  "OZGovernor": OZGovernorAbi,
  "SolidlyVotingEscrow": SolidlyVotingEscrowAbi,
};
