#!/usr/bin/env node
/**
 * Generate browser-pure TypeScript ABI modules from the canonical JSON ABIs.
 *
 * Source of truth stays at <repo>/src/abi/*.json (written by
 * scripts/extract-abis.mjs from forge artifacts, plus the hand-maintained
 * ERC20.json and external/ set). This script derives packages/core/src/abis/
 * from it at build time, so @poa/core never touches the filesystem at runtime
 * and bundlers see plain TS modules.
 *
 * Generated files are committed (they are part of the package source) but
 * regenerated on every core build — a drifted checkout self-heals.
 */
import { readFileSync, writeFileSync, readdirSync, mkdirSync, rmSync } from 'node:fs';
import { dirname, join, resolve, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repoAbiDir = resolve(here, '..', '..', '..', 'src', 'abi');
const outDir = resolve(here, '..', 'src', 'abis');

const HEADER = '// GENERATED by packages/core/scripts/gen-abis.mjs — do not edit.\n'
  + '// Source of truth: src/abi/*.json at the repo root (see scripts/extract-abis.mjs).\n';

/** "TaskManagerNew" -> exported const name "TaskManagerNewAbi" */
function constName(base) {
  return `${base.replace(/[^A-Za-z0-9_]/g, '_')}Abi`;
}

function emitAbiModule(outPath, name, abi) {
  const body = `${HEADER}\nexport const ${constName(name)} = ${JSON.stringify(abi, null, 2)} as const;\n\nexport default ${constName(name)};\n`;
  writeFileSync(outPath, body);
}

function readAbis(dir) {
  let files = [];
  try {
    files = readdirSync(dir).filter((f) => f.endsWith('.json'));
  } catch {
    return [];
  }
  return files.map((f) => {
    const abi = JSON.parse(readFileSync(join(dir, f), 'utf-8'));
    if (!Array.isArray(abi)) throw new Error(`${join(dir, f)} is not a bare ABI array`);
    return { name: basename(f, '.json'), abi };
  });
}

// Validate the source BEFORE any destructive step: a checkout (or packed
// tarball) without ../../src/abi must leave the committed generated modules
// untouched rather than deleting them and then failing.
const top = readAbis(repoAbiDir);
const external = readAbis(join(repoAbiDir, 'external'));
if (top.length === 0) {
  console.error(`gen-abis: no ABIs found at ${repoAbiDir} — leaving existing generated modules untouched`);
  process.exit(1);
}

rmSync(outDir, { recursive: true, force: true });
mkdirSync(join(outDir, 'external'), { recursive: true });

for (const { name, abi } of top) emitAbiModule(join(outDir, `${name}.ts`), name, abi);
for (const { name, abi } of external) emitAbiModule(join(outDir, 'external', `${name}.ts`), name, abi);

// Index: named re-exports + the ALL_ABIS registry (feeds getAbi + the error catalog).
const indexLines = [HEADER];
for (const { name } of top) {
  indexLines.push(`import { ${constName(name)} } from './${name}';`);
}
for (const { name } of external) {
  indexLines.push(`import { ${constName(name)} } from './external/${name}';`);
}
indexLines.push('');
for (const { name } of top) indexLines.push(`export { ${constName(name)} };`);
for (const { name } of external) indexLines.push(`export { ${constName(name)} };`);
indexLines.push('');
indexLines.push('/** Every first-party POP ABI, keyed by its historical abi/ file base name. */');
indexLines.push('export const ALL_ABIS: Record<string, readonly unknown[]> = {');
for (const { name } of top) indexLines.push(`  ${JSON.stringify(name)}: ${constName(name)},`);
indexLines.push('};');
indexLines.push('');
indexLines.push('/** Third-party governance ABIs (probe targets), keyed by file base name. */');
indexLines.push('export const EXTERNAL_ABIS: Record<string, readonly unknown[]> = {');
for (const { name } of external) indexLines.push(`  ${JSON.stringify(name)}: ${constName(name)},`);
indexLines.push('};');
indexLines.push('');
writeFileSync(join(outDir, 'index.ts'), indexLines.join('\n'));

console.log(`gen-abis: wrote ${top.length} ABIs + ${external.length} external ABIs to ${outDir}`);
