/**
 * generate-cli-docs — emit docs/reference/cli/*.md from the recorded yargs
 * command tree (scripts/lib/cli-tree.ts).
 *
 *   yarn docs:gen             regenerate the reference in place
 *   yarn docs:gen --check     regenerate to memory, byte-compare against disk,
 *                             exit 1 listing drifted files (used by CI)
 *
 * Output is deterministic: commands in registration order, flags sorted
 * alphabetically, no timestamps — so `--check` is a pure byte comparison.
 */

import * as fs from 'fs';
import * as path from 'path';
import {
  buildCliTree,
  buildTopLevelCommands,
  getBuildDiagnostics,
  GLOBAL_FLAGS,
  CliCommand,
  CliDomain,
  OptSpec,
} from './lib/cli-tree';

const ROOT = path.resolve(__dirname, '..');
const OUT_DIR = path.join(ROOT, 'docs', 'reference', 'cli');
const BANNER = '<!-- AUTO-GENERATED by scripts/generate-cli-docs.ts — do not edit. Regenerate: yarn docs:gen -->';

const GLOBAL_FLAG_NAMES = Object.keys(GLOBAL_FLAGS).map((k) => `--${k}`).join(', ');
const FOOTER = `_Global flags: ${GLOBAL_FLAG_NAMES} (see [index.md](index.md))_`;

// ---------------------------------------------------------------------------
// Markdown rendering
// ---------------------------------------------------------------------------

function escapeCell(text: string): string {
  return text.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ').trim();
}

function renderDefault(value: unknown): string {
  if (value === undefined) return '-';
  if (typeof value === 'string') return value === '' ? '`""`' : `\`${escapeCell(value)}\``;
  return `\`${escapeCell(JSON.stringify(value))}\``;
}

function renderDescription(spec: OptSpec): string {
  let desc = spec.description ?? '';
  if (spec.choices && spec.choices.length > 0) {
    const choices = spec.choices.map((c) => `\`${c}\``).join(', ');
    desc = desc ? `${desc} (choices: ${choices})` : `Choices: ${choices}`;
  }
  return escapeCell(desc) || '-';
}

function renderFlagCell(name: string, spec: OptSpec): string {
  const parts = [`\`--${name}\``];
  for (const alias of spec.aliases ?? []) {
    parts.push(alias.length === 1 ? `\`-${alias}\`` : `\`--${alias}\``);
  }
  return parts.join(', ');
}

function renderFlagsTable(options: Record<string, OptSpec>): string[] {
  const names = Object.keys(options).sort();
  const lines = [
    '| Flag | Type | Required | Default | Description |',
    '| --- | --- | --- | --- | --- |',
  ];
  for (const name of names) {
    const spec = options[name];
    lines.push(
      `| ${renderFlagCell(name, spec)} | ${spec.type ?? '-'} | ${spec.required ? 'yes' : 'no'} | ${renderDefault(spec.default)} | ${renderDescription(spec)} |`,
    );
  }
  return lines;
}

function renderPositionalsTable(positionals: OptSpec[]): string[] {
  const lines = [
    '| Positional | Type | Required | Default | Description |',
    '| --- | --- | --- | --- | --- |',
  ];
  for (const spec of positionals) {
    const name = spec.variadic ? `\`<${spec.name}..>\`` : `\`<${spec.name}>\``;
    lines.push(
      `| ${name} | ${spec.type ?? '-'} | ${spec.required ? 'yes' : 'no'} | ${renderDefault(spec.default)} | ${renderDescription(spec)} |`,
    );
  }
  return lines;
}

function usageLine(command: CliCommand): string {
  const positionals = command.positionals
    .map((p) => {
      const inner = p.variadic ? `${p.name}..` : p.name;
      return p.required ? `<${inner}>` : `[${inner}]`;
    })
    .join(' ');
  return [command.fullName, positionals, '[flags]'].filter(Boolean).join(' ');
}

function renderCommand(command: CliCommand, depth: number): string[] {
  const heading = '#'.repeat(Math.min(2 + depth, 6));
  const lines: string[] = [];
  lines.push(`${heading} ${command.fullName}`, '');
  if (command.description) lines.push(command.description, '');
  lines.push('```text', usageLine(command), '```', '');
  if (command.positionals.length > 0) {
    lines.push(...renderPositionalsTable(command.positionals), '');
  }
  if (Object.keys(command.options).length > 0) {
    lines.push(...renderFlagsTable(command.options), '');
  }
  for (const sub of command.subcommands ?? []) {
    lines.push(...renderCommand(sub, depth + 1));
  }
  return lines;
}

function renderDomainPage(domain: CliDomain): string {
  const lines: string[] = [BANNER, '', `# pop ${domain.domain}`, '', domain.description, ''];
  for (const command of domain.commands) {
    lines.push(...renderCommand(command, 0));
  }
  lines.push(FOOTER, '');
  return lines.join('\n');
}

function renderIndexPage(tree: CliDomain[], topLevel: CliCommand[]): string {
  const lines: string[] = [
    BANNER,
    '',
    '# pop CLI Reference',
    '',
    'Command reference generated from the yargs command tree. Regenerate with `yarn docs:gen`; CI verifies it with `yarn docs:check`.',
    '',
    '| Domain | Description | Commands | Reference |',
    '| --- | --- | --- | --- |',
  ];
  for (const domain of tree) {
    lines.push(
      `| \`${domain.domain}\` | ${escapeCell(domain.description)} | ${domain.commands.length} | [${domain.domain}.md](${domain.domain}.md) |`,
    );
  }
  if (topLevel.length > 0) {
    lines.push('', '## Top-level commands', '', 'Run directly as `pop <command>` (not under a domain):', '');
    for (const command of topLevel) {
      lines.push(...renderCommand(command, 0));
    }
  }
  lines.push('', '## Global flags', '', 'Available on every command:', '');
  for (const name of Object.keys(GLOBAL_FLAGS)) {
    const spec = GLOBAL_FLAGS[name];
    const aliases = (spec.aliases ?? []).map((a) => (a.length === 1 ? `\`-${a}\`` : `\`--${a}\``));
    const label = [`\`--${name}\``, ...aliases].join(', ');
    const details: string[] = [];
    if (spec.type) details.push(spec.type);
    if (spec.default !== undefined) details.push(`default: ${JSON.stringify(spec.default)}`);
    const suffix = details.length > 0 ? ` (${details.join(', ')})` : '';
    lines.push(`- ${label} — ${spec.description ?? ''}${suffix}`);
  }
  lines.push('');
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function generate(): Map<string, string> {
  const tree = buildCliTree();
  const topLevel = buildTopLevelCommands();
  const files = new Map<string, string>();
  files.set('index.md', renderIndexPage(tree, topLevel));
  for (const domain of tree) {
    files.set(`${domain.domain}.md`, renderDomainPage(domain));
  }
  return files;
}

function main(): void {
  const checkMode = process.argv.includes('--check');
  const files = generate();
  const diagnostics = getBuildDiagnostics();

  if (checkMode) {
    const drifted: string[] = [];
    for (const [name, content] of files) {
      const target = path.join(OUT_DIR, name);
      if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== content) {
        drifted.push(path.relative(ROOT, target));
      }
    }
    // Stale pages (e.g. a removed domain) count as drift too.
    if (fs.existsSync(OUT_DIR)) {
      for (const entry of fs.readdirSync(OUT_DIR)) {
        if (entry.endsWith('.md') && !files.has(entry)) {
          drifted.push(path.relative(ROOT, path.join(OUT_DIR, entry)));
        }
      }
    }
    if (drifted.length > 0) {
      for (const name of drifted.sort()) console.error(name);
      process.exit(1);
    }
    return;
  }

  for (const diag of diagnostics) {
    console.error(`warning: builder for '${diag.command}' threw during recording: ${diag.error}`);
  }

  fs.mkdirSync(OUT_DIR, { recursive: true });
  let written = 0;
  for (const [name, content] of files) {
    const target = path.join(OUT_DIR, name);
    if (fs.existsSync(target) && fs.readFileSync(target, 'utf8') === content) continue;
    fs.writeFileSync(target, content);
    console.log(`wrote ${path.relative(ROOT, target)}`);
    written += 1;
  }
  for (const entry of fs.readdirSync(OUT_DIR)) {
    if (entry.endsWith('.md') && !files.has(entry)) {
      fs.unlinkSync(path.join(OUT_DIR, entry));
      console.log(`removed ${path.relative(ROOT, path.join(OUT_DIR, entry))}`);
      written += 1;
    }
  }
  console.log(
    written === 0
      ? `docs/reference/cli up to date (${files.size} pages)`
      : `docs/reference/cli regenerated (${files.size} pages, ${written} changed)`,
  );
}

main();
