/**
 * generate-cli-docs — emit docs/reference/cli/*.md from the recorded yargs
 * command tree (scripts/lib/cli-tree.ts).
 *
 *   yarn docs:gen             regenerate the reference in place
 *   yarn docs:gen --check     regenerate to memory, byte-compare against disk,
 *                             exit 1 listing drifted files (used by CI)
 *
 * Output is deterministic: commands in registration order, flags sorted
 * alphabetically, no timestamps — so `--check` is a pure byte comparison.
 */

import * as fs from 'fs';
import * as path from 'path';
import {
  buildCliTree,
  buildTopLevelCommands,
  getBuildDiagnostics,
  GLOBAL_FLAGS,
  CliCommand,
  CliDomain,
  OptSpec,
} from './lib/cli-tree';
import { safetyFor } from './lib/safety-map';

const ROOT = path.resolve(__dirname, '..');
const OUT_DIR = path.join(ROOT, 'docs', 'reference', 'cli');
const BANNER = '<!-- AUTO-GENERATED by scripts/generate-cli-docs.ts — do not edit. Regenerate: yarn docs:gen -->';

const GLOBAL_FLAG_NAMES = Object.keys(GLOBAL_FLAGS).map((k) => `--${k}`).join(', ');
const FOOTER = `_Global flags: ${GLOBAL_FLAG_NAMES} (see [index.md](index.md))_`;

// ---------------------------------------------------------------------------
// Markdown rendering
// ---------------------------------------------------------------------------

function escapeCell(text: string): string {
  return text.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ').trim();
}

function renderDefault(value: unknown): string {
  if (value === undefined) return '-';
  if (typeof value === 'string') return value === '' ? '`""`' : `\`${escapeCell(value)}\``;
  return `\`${escapeCell(JSON.stringify(value))}\``;
}

function renderDescription(spec: OptSpec): string {
  let desc = spec.description ?? '';
  if (spec.choices && spec.choices.length > 0) {
    const choices = spec.choices.map((c) => `\`${c}\``).join(', ');
    desc = desc ? `${desc} (choices: ${choices})` : `Choices: ${choices}`;
  }
  return escapeCell(desc) || '-';
}

function renderFlagCell(name: string, spec: OptSpec): string {
  const parts = [`\`--${name}\``];
  for (const alias of spec.aliases ?? []) {
    parts.push(alias.length === 1 ? `\`-${alias}\`` : `\`--${alias}\``);
  }
  return parts.join(', ');
}

function renderFlagsTable(options: Record<string, OptSpec>): string[] {
  const names = Object.keys(options).sort();
  const lines = [
    '| Flag | Type | Required | Default | Description |',
    '| --- | --- | --- | --- | --- |',
  ];
  for (const name of names) {
    const spec = options[name];
    lines.push(
      `| ${renderFlagCell(name, spec)} | ${spec.type ?? '-'} | ${spec.required ? 'yes' : 'no'} | ${renderDefault(spec.default)} | ${renderDescription(spec)} |`,
    );
  }
  return lines;
}

function renderPositionalsTable(positionals: OptSpec[]): string[] {
  const lines = [
    '| Positional | Type | Required | Default | Description |',
    '| --- | --- | --- | --- | --- |',
  ];
  for (const spec of positionals) {
    const name = spec.variadic ? `\`<${spec.name}..>\`` : `\`<${spec.name}>\``;
    lines.push(
      `| ${name} | ${spec.type ?? '-'} | ${spec.required ? 'yes' : 'no'} | ${renderDefault(spec.default)} | ${renderDescription(spec)} |`,
    );
  }
  return lines;
}

function usageLine(command: CliCommand): string {
  const positionals = command.positionals
    .map((p) => {
      const inner = p.variadic ? `${p.name}..` : p.name;
      return p.required ? `<${inner}>` : `[${inner}]`;
    })
    .join(' ');
  return [command.fullName, positionals, '[flags]'].filter(Boolean).join(' ');
}

function renderCommand(command: CliCommand, depth: number): string[] {
  const heading = '#'.repeat(Math.min(2 + depth, 6));
  const lines: string[] = [];
  lines.push(`${heading} ${command.fullName}`, '');
  if (command.description) lines.push(command.description, '');
  lines.push('```text', usageLine(command), '```', '');
  if (command.positionals.length > 0) {
    lines.push(...renderPositionalsTable(command.positionals), '');
  }
  if (Object.keys(command.options).length > 0) {
    lines.push(...renderFlagsTable(command.options), '');
  }
  for (const sub of command.subcommands ?? []) {
    lines.push(...renderCommand(sub, depth + 1));
  }
  return lines;
}

function renderDomainPage(domain: CliDomain): string {
  const lines: string[] = [BANNER, '', `# pop ${domain.domain}`, '', domain.description, ''];
  for (const command of domain.commands) {
    lines.push(...renderCommand(command, 0));
  }
  lines.push(FOOTER, '');
  return lines.join('\n');
}

function renderIndexPage(tree: CliDomain[], topLevel: CliCommand[]): string {
  const lines: string[] = [
    BANNER,
    '',
    '# pop CLI Reference',
    '',
    'Command reference generated from the yargs command tree. Regenerate with `yarn docs:gen`; CI verifies it with `yarn docs:check`.',
    '',
    '| Domain | Description | Commands | Reference |',
    '| --- | --- | --- | --- |',
  ];
  for (const domain of tree) {
    lines.push(
      `| \`${domain.domain}\` | ${escapeCell(domain.description)} | ${domain.commands.length} | [${domain.domain}.md](${domain.domain}.md) |`,
    );
  }
  if (topLevel.length > 0) {
    lines.push('', '## Top-level commands', '', 'Run directly as `pop <command>` (not under a domain):', '');
    for (const command of topLevel) {
      lines.push(...renderCommand(command, 0));
    }
  }
  lines.push('', '## Global flags', '', 'Available on every command:', '');
  for (const name of Object.keys(GLOBAL_FLAGS)) {
    const spec = GLOBAL_FLAGS[name];
    const aliases = (spec.aliases ?? []).map((a) => (a.length === 1 ? `\`-${a}\`` : `\`--${a}\``));
    const label = [`\`--${name}\``, ...aliases].join(', ');
    const details: string[] = [];
    if (spec.type) details.push(spec.type);
    if (spec.default !== undefined) details.push(`default: ${JSON.stringify(spec.default)}`);
    const suffix = details.length > 0 ? ` (${details.join(', ')})` : '';
    lines.push(`- ${label} — ${spec.description ?? ''}${suffix}`);
  }
  lines.push('');
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function manifestOption(spec: OptSpec): Record<string, unknown> {
  const out: Record<string, unknown> = { type: spec.type ?? 'string' };
  if (spec.description) out.description = spec.description;
  if (spec.default !== undefined) out.default = spec.default;
  if (spec.choices && spec.choices.length) out.choices = spec.choices;
  if (spec.required) out.required = true;
  if (spec.aliases && spec.aliases.length) out.aliases = spec.aliases;
  return out;
}

function manifestCommand(domain: string, cmd: CliCommand, entries: any[]): void {
  const isGroup = (cmd.subcommands?.length ?? 0) > 0;
  const safety = safetyFor(cmd.fullName.replace(/^pop /, ''));
  const broadcasts = safety?.broadcasts ?? false;
  entries.push({
    name: cmd.fullName.replace(/^pop /, ''),
    kind: isGroup ? 'group' : 'command',
    description: cmd.description,
    // readOnly = cannot broadcast a transaction. Check sideEffects too: a
    // readOnly command may still publish to IPFS via --pin, or write files.
    readOnly: !broadcasts,
    broadcasts,
    destructive: safety?.destructive ?? false,
    sideEffects: safety?.sideEffects ?? [],
    positionals: cmd.positionals.map((pSpec) => ({
      name: pSpec.name,
      type: pSpec.type ?? 'string',
      ...(pSpec.description ? { description: pSpec.description } : {}),
      ...(pSpec.required ? { required: true } : {}),
    })),
    options: Object.fromEntries(
      Object.entries(cmd.options)
        .sort(([a], [b]) => a.localeCompare(b))
        .map(([name, spec]) => [name, manifestOption(spec)])
    ),
  });
  for (const sub of cmd.subcommands ?? []) manifestCommand(domain, sub, entries);
}

/**
 * The machine-readable command manifest. The read/write split here is the
 * CURATED one from scripts/lib/safety-map.ts, drift-checked against the
 * source by test/docs/manifest-safety.test.ts — integrators should consume
 * this instead of re-deriving it (and getting `vote announce-all` wrong).
 */
function renderManifest(tree: CliDomain[], topLevel: CliCommand[]): string {
  const commands: any[] = [];
  for (const domain of tree) {
    for (const cmd of domain.commands) manifestCommand(domain.domain, cmd, commands);
  }
  for (const cmd of topLevel) {
    const safety = safetyFor(cmd.name);
    commands.push({
      name: cmd.name,
      kind: 'command',
      description: cmd.description,
      readOnly: !(safety?.broadcasts ?? false),
      broadcasts: safety?.broadcasts ?? false,
      destructive: safety?.destructive ?? false,
      sideEffects: safety?.sideEffects ?? [],
      positionals: [],
      options: Object.fromEntries(
        Object.entries(cmd.options).sort(([a], [b]) => a.localeCompare(b)).map(([n, sp]) => [n, manifestOption(sp)])
      ),
    });
  }
  const manifest = {
    package: '@poa-box/cli',
    schemaVersion: 1,
    notes: [
      'readOnly means "cannot broadcast a transaction". A readOnly command may still have sideEffects — ipfs-pin(--pin) publishes publicly and irreversibly when --pin is passed.',
      'destructive commands require an explicit --yes (or POP_ASSUME_YES=1) in every non-interactive context; --json is never consent.',
      'POP_READONLY=1 makes the process structurally unable to sign or pin. POP_ADDRESS/--address serves identity-scoped reads without a key.',
      'The agent runtime commands (pop agent, pop brain) live in @poa-box/agent and are not covered here.',
    ],
    globalFlags: Object.fromEntries(
      Object.entries(GLOBAL_FLAGS).map(([n, sp]) => [n, manifestOption(sp)])
    ),
    commands,
  };
  return JSON.stringify(manifest, null, 2) + '\n';
}

function generate(): Map<string, string> {
  const tree = buildCliTree();
  const topLevel = buildTopLevelCommands();
  const files = new Map<string, string>();
  files.set('index.md', renderIndexPage(tree, topLevel));
  for (const domain of tree) {
    files.set(`${domain.domain}.md`, renderDomainPage(domain));
  }
  files.set('manifest.json', renderManifest(tree, topLevel));
  return files;
}

function main(): void {
  const checkMode = process.argv.includes('--check');
  const files = generate();
  const diagnostics = getBuildDiagnostics();

  if (checkMode) {
    const drifted: string[] = [];
    for (const [name, content] of files) {
      const target = path.join(OUT_DIR, name);
      if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== content) {
        drifted.push(path.relative(ROOT, target));
      }
    }
    // Stale pages (e.g. a removed domain) count as drift too.
    if (fs.existsSync(OUT_DIR)) {
      for (const entry of fs.readdirSync(OUT_DIR)) {
        if ((entry.endsWith('.md') || entry === 'manifest.json') && !files.has(entry)) {
          drifted.push(path.relative(ROOT, path.join(OUT_DIR, entry)));
        }
      }
    }
    const generatedTarget = path.join(ROOT, 'src', 'generated', 'cli-manifest.json');
    if (!fs.existsSync(generatedTarget) || fs.readFileSync(generatedTarget, 'utf8') !== files.get('manifest.json')) {
      drifted.push(path.relative(ROOT, generatedTarget));
    }
    if (drifted.length > 0) {
      for (const name of drifted.sort()) console.error(name);
      process.exit(1);
    }
    return;
  }

  for (const diag of diagnostics) {
    console.error(`warning: builder for '${diag.command}' threw during recording: ${diag.error}`);
  }

  fs.mkdirSync(OUT_DIR, { recursive: true });
  // Mirror for runtime consumers (pop mcp): imported via resolveJsonModule so
  // tsc emits it into dist/generated/.
  const generatedDir = path.join(ROOT, 'src', 'generated');
  fs.mkdirSync(generatedDir, { recursive: true });
  const manifestContent = files.get('manifest.json')!;
  const generatedTarget = path.join(generatedDir, 'cli-manifest.json');
  if (!fs.existsSync(generatedTarget) || fs.readFileSync(generatedTarget, 'utf8') !== manifestContent) {
    fs.writeFileSync(generatedTarget, manifestContent);
    console.log(`wrote ${path.relative(ROOT, generatedTarget)}`);
  }
  let written = 0;
  for (const [name, content] of files) {
    const target = path.join(OUT_DIR, name);
    if (fs.existsSync(target) && fs.readFileSync(target, 'utf8') === content) continue;
    fs.writeFileSync(target, content);
    console.log(`wrote ${path.relative(ROOT, target)}`);
    written += 1;
  }
  for (const entry of fs.readdirSync(OUT_DIR)) {
    if ((entry.endsWith('.md') || entry === 'manifest.json') && !files.has(entry)) {
      fs.unlinkSync(path.join(OUT_DIR, entry));
      console.log(`removed ${path.relative(ROOT, path.join(OUT_DIR, entry))}`);
      written += 1;
    }
  }
  console.log(
    written === 0
      ? `docs/reference/cli up to date (${files.size} pages)`
      : `docs/reference/cli regenerated (${files.size} pages, ${written} changed)`,
  );
}

main();
