/**
 * pop brain migrate — one-shot import of a hand-written brain knowledge
 * file into a CRDT Automerge doc. Step 8 of the brain plan.
 *
 * Usage:
 *   pop brain migrate --from agent/brain/Knowledge/shared.md \
 *                     --doc pop.brain.shared
 *
 * Flow:
 *   1. Read the markdown file from disk.
 *   2. parseSharedMarkdown → SharedBrainDoc (rules + lessons).
 *   3. --dry-run: print the parsed structure and exit.
 *   4. Otherwise: check that the target doc is empty (or --force),
 *      then apply the parsed content via applyBrainChange. This
 *      auto-signs + auto-publishes via the step 5 gossipsub layer
 *      so any live subscriber picks up the migration immediately.
 *   5. Write a DEPRECATED banner to the top of the source file
 *      pointing agents at <docId>.generated.md as the new source
 *      of truth. Original content is preserved below the banner
 *      for historical reference — the banner is opt-in.
 *
 * Idempotence: running the command twice on a doc that already has
 * content errors out unless --force is supplied. This protects
 * against accidental clobbering during a fumbled migration.
 */

import type { Argv, ArgumentsCamelCase } from 'yargs';
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { resolve } from 'path';
import {
  openBrainDoc,
  applyBrainChange,
  stopBrainNode,
} from '../../lib/brain';
import {
  parseSharedMarkdown,
  type ParsedBrainDoc,
  type MigrationContext,
} from '../../lib/brain-migrate';
import * as output from '@poa/cli/lib/output';

interface MigrateArgs {
  from: string;
  doc: string;
  force?: boolean;
  merge?: boolean;
  dryRun?: boolean;
  currentHb?: number;
  author?: string;
  noBanner?: boolean;
}

/**
 * Banner injected at the top of the source hand-written file after a
 * successful migration. Keeps the original content below so git
 * history + human review are preserved; future hand-edits still
 * survive but are flagged as out-of-sync with the CRDT.
 */
const DEPRECATED_BANNER = (docId: string, headCid: string) => `<!-- DEPRECATED: migrated to ${docId} at CID ${headCid} -->
<!-- Source of truth is now agent/brain/Knowledge/${docId}.generated.md -->
<!-- regenerated by \`pop brain snapshot --doc ${docId}\` at end of every heartbeat. -->
<!-- Edit via \`pop brain\` CLI; hand-edits here will NOT propagate. -->

`;

/**
 * Pure helper: compute which parsed entries should be appended to an
 * existing list vs skipped because an entry with the same `id` already
 * exists. Extracted so the --merge dedup logic is unit-testable
 * independent of the brain daemon / Automerge doc layer.
 *
 * Entries without an `id` are ALWAYS added (we can't dedup what has no
 * key). Callers should ensure parsed entries have ids if they want
 * dedup semantics — parseSharedMarkdown always assigns an id via
 * slugify fallback, so in practice every parsed lesson has an id.
 */
export function computeMergeDelta<T extends { id?: string }>(
  existing: readonly T[],
  parsed: readonly T[],
): { toAdd: T[]; skippedCount: number } {
  const existingIds = new Set<string>(
    existing
      .map((e) => e?.id)
      .filter((id): id is string => typeof id === 'string'),
  );
  const toAdd: T[] = [];
  let skippedCount = 0;
  for (const entry of parsed) {
    if (entry.id && existingIds.has(entry.id)) {
      skippedCount += 1;
      continue;
    }
    toAdd.push(entry);
  }
  return { toAdd, skippedCount };
}

export const migrateHandler = {
  builder: (yargs: Argv) =>
    yargs
      .option('from', {
        describe: 'Path to the hand-written markdown file to migrate',
        type: 'string',
        demandOption: true,
      })
      .option('doc', {
        describe: 'Target brain document ID (e.g. pop.brain.shared)',
        type: 'string',
        demandOption: true,
      })
      .option('force', {
        describe: 'Re-migrate even if the target doc already has content (DESTRUCTIVE: clears existing lessons/rules before re-seeding)',
        type: 'boolean',
        default: false,
      })
      .option('merge', {
        describe: 'Non-destructive append: migrate new entries into an existing doc, deduping by id (mutually exclusive with --force)',
        type: 'boolean',
        default: false,
      })
      .option('dry-run', {
        describe: 'Parse and print the structured output without persisting',
        type: 'boolean',
        default: false,
      })
      .option('current-hb', {
        describe:
          'Current heartbeat number for HB#→timestamp estimation (default 270)',
        type: 'number',
        default: 270,
      })
      .option('author', {
        describe: 'Default author for sections without explicit attribution',
        type: 'string',
        default: 'migration',
      })
      .option('no-banner', {
        describe:
          'Do NOT write a DEPRECATED banner to the source file after migration',
        type: 'boolean',
        default: false,
      }),

  handler: async (argv: ArgumentsCamelCase<MigrateArgs>) => {
    const srcPath = resolve(argv.from);
    const docId = argv.doc;

    try {
      if (argv.force && argv.merge) {
        output.error(
          '--force and --merge are mutually exclusive. --force clears and re-seeds; ' +
            '--merge appends dedup-by-id into existing content. Pick one.',
        );
        process.exitCode = 1;
        return;
      }

      if (!existsSync(srcPath)) {
        output.error(`Source file not found: ${srcPath}`);
        process.exitCode = 1;
        return;
      }

      const raw = readFileSync(srcPath, 'utf8');
      const now = Math.floor(Date.now() / 1000);
      const currentHB = argv.currentHb ?? 270;
      const ctx: MigrationContext = {
        defaultAuthor: argv.author ?? 'migration',
        defaultTimestamp: now,
        timestampForHB: (hb: number) => now - (currentHB - hb) * 15 * 60,
      };

      const parsed: ParsedBrainDoc = parseSharedMarkdown(raw, ctx);

      if (argv.dryRun) {
        if (output.isJsonMode()) {
          output.json({ status: 'dry-run', docId, parsed });
        } else {
          console.log('');
          console.log(`  Dry-run migration: ${srcPath}`);
          console.log(`  Target doc:        ${docId}`);
          console.log('  ' + '─'.repeat(60));
          console.log(`  Rules:   ${parsed.rules.length}`);
          console.log(`  Lessons: ${parsed.lessons.length}`);
          console.log('');
          console.log('  First 3 rules:');
          for (const r of parsed.rules.slice(0, 3)) {
            console.log(`    - ${r.id}: ${(r.text ?? '').slice(0, 80).replace(/\n/g, ' ')}...`);
          }
          console.log('  First 3 lessons:');
          for (const l of parsed.lessons.slice(0, 3)) {
            console.log(`    - ${l.id}: ${(l.title ?? '').slice(0, 80)}`);
          }
          console.log('');
          console.log('  No changes persisted (--dry-run).');
          console.log('');
        }
        return;
      }

      // Refuse to overwrite an existing doc unless --force or --merge.
      const existing = await openBrainDoc(docId);
      const alreadyHasContent =
        existing.headCid !== null &&
        existing.doc &&
        (Object.keys(existing.doc).length > 0);
      if (alreadyHasContent && !argv.force && !argv.merge) {
        output.error(
          `Target doc "${docId}" already has content at head ${existing.headCid}. ` +
            'Re-run with --merge to append new entries non-destructively (dedup by id), ' +
            'or --force to clear-and-reseed (DESTRUCTIVE).',
        );
        process.exitCode = 1;
        return;
      }

      // Merge-mode stats: set in the change callback, read after the apply.
      let lessonsAdded = 0;
      let lessonsSkipped = 0;
      let rulesAdded = 0;
      let rulesSkipped = 0;

      // Apply the parsed state in a single Automerge change so the
      // entire migration lands as one content-addressed snapshot.
      const result = await applyBrainChange(docId, (doc: any) => {
        if (!doc.rules) doc.rules = [];
        if (!doc.lessons) doc.lessons = [];
        if (argv.force) {
          // Force re-migration: clear existing and re-seed.
          doc.rules.splice(0, doc.rules.length);
          doc.lessons.splice(0, doc.lessons.length);
        }
        if (argv.merge) {
          // Non-destructive append: dedup by id against existing entries.
          const rulesDelta = computeMergeDelta(doc.rules as any[], parsed.rules as any[]);
          const lessonsDelta = computeMergeDelta(doc.lessons as any[], parsed.lessons as any[]);
          for (const r of rulesDelta.toAdd) doc.rules.push({ ...r });
          for (const l of lessonsDelta.toAdd) doc.lessons.push({ ...l });
          rulesAdded = rulesDelta.toAdd.length;
          rulesSkipped = rulesDelta.skippedCount;
          lessonsAdded = lessonsDelta.toAdd.length;
          lessonsSkipped = lessonsDelta.skippedCount;
          return;
        }
        // Legacy / --force path: append everything unconditionally.
        for (const r of parsed.rules) {
          doc.rules.push({ ...r });
          rulesAdded += 1;
        }
        for (const l of parsed.lessons) {
          doc.lessons.push({ ...l });
          lessonsAdded += 1;
        }
      });

      // Write the deprecated banner to the source file unless
      // explicitly suppressed. Keep the original content below.
      if (!argv.noBanner) {
        const banner = DEPRECATED_BANNER(docId, result.headCid);
        if (!raw.includes('DEPRECATED: migrated to')) {
          writeFileSync(srcPath, banner + raw);
        }
      }

      if (output.isJsonMode()) {
        output.json({
          status: 'ok',
          docId,
          headCid: result.headCid,
          mode: argv.merge ? 'merge' : argv.force ? 'force' : 'fresh',
          rulesAdded,
          rulesSkipped,
          lessonsAdded,
          lessonsSkipped,
          // Back-compat keys — total parsed, not added.
          rulesMigrated: parsed.rules.length,
          lessonsMigrated: parsed.lessons.length,
          sourceFile: srcPath,
          bannerWritten: !argv.noBanner,
        });
      } else {
        console.log('');
        console.log(`  Migration complete: ${srcPath} → ${docId}`);
        console.log(`  Mode: ${argv.merge ? 'merge' : argv.force ? 'force' : 'fresh'}`);
        console.log(`  New head CID: ${result.headCid}`);
        if (argv.merge) {
          console.log(`  Rules:   +${rulesAdded} added, ${rulesSkipped} skipped (dup id)`);
          console.log(`  Lessons: +${lessonsAdded} added, ${lessonsSkipped} skipped (dup id)`);
        } else {
          console.log(`  Rules:   ${rulesAdded}`);
          console.log(`  Lessons: ${lessonsAdded}`);
        }
        if (!argv.noBanner) {
          console.log(`  Banner written to source file.`);
        }
        console.log('');
        console.log(`  Run \`pop brain read --doc ${docId}\` to inspect.`);
        console.log(`  Run \`pop brain snapshot --doc ${docId}\` to produce the .generated.md.`);
        console.log('');
      }
    } catch (err: any) {
      output.error(err.message);
      process.exitCode = 1;
    } finally {
      await stopBrainNode();
    }
  },
};
