/**
 * pop brain migrate-projects — one-shot import of a hand-written
 * projects.md file into a brain projects doc. Same shape as
 * `pop brain migrate` (#296) but for pop.brain.projects instead of
 * pop.brain.shared. Parses the "Active Projects" H2 section only.
 *
 * Usage:
 *   pop brain migrate-projects \
 *     --from agent/brain/Knowledge/projects.md \
 *     --doc pop.brain.projects.test \
 *     --dry-run
 *
 * Dry-run reports parse results without persisting. Without --dry-run,
 * refuses to write if the target doc already has content unless --force.
 */

import type { Argv, ArgumentsCamelCase } from 'yargs';
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { resolve } from 'path';
import {
  openBrainDoc,
  applyBrainChange,
  stopBrainNode,
} from '../../lib/brain';
import { parseProjectsMarkdown } from '../../lib/brain-migrate-projects';
import type { MigrationContext } from '../../lib/brain-migrate';
import type { ProjectsBrainDoc } from '../../lib/brain-projections';
import * as output from '@poa-box/cli/lib/output';

interface MigrateProjectsArgs {
  from: string;
  doc: string;
  force?: boolean;
  dryRun?: boolean;
  author?: string;
  currentHb?: number;
  noBanner?: boolean;
}

const DEPRECATED_BANNER = (docId: string, headCid: string) => `<!-- DEPRECATED: migrated to ${docId} at CID ${headCid} -->
<!-- Source of truth is now agent/brain/Knowledge/${docId}.generated.md -->
<!-- regenerated by \`pop brain snapshot --doc ${docId}\` at end of every heartbeat. -->
<!-- Edit via \`pop brain\` CLI; hand-edits here will NOT propagate. -->

`;

export const migrateProjectsHandler = {
  builder: (yargs: Argv) =>
    yargs
      .option('from', {
        describe: 'Path to the hand-written projects.md to migrate',
        type: 'string',
        demandOption: true,
      })
      .option('doc', {
        describe: 'Target brain document ID (typically pop.brain.projects)',
        type: 'string',
        demandOption: true,
      })
      .option('force', {
        describe: 'Re-migrate even if the target doc already has live projects',
        type: 'boolean',
        default: false,
      })
      .option('dry-run', {
        describe: 'Parse and print the structured output without persisting',
        type: 'boolean',
        default: false,
      })
      .option('current-hb', {
        describe: 'Current heartbeat number for HB#→timestamp estimation (default 285)',
        type: 'number',
        default: 285,
      })
      .option('author', {
        describe: 'Default author for projects without explicit attribution',
        type: 'string',
        default: 'migration',
      })
      .option('no-banner', {
        describe: 'Do NOT write a DEPRECATED banner to the source file after migration',
        type: 'boolean',
        default: false,
      }),

  handler: async (argv: ArgumentsCamelCase<MigrateProjectsArgs>) => {
    const srcPath = resolve(argv.from);
    const docId = argv.doc;

    try {
      if (!existsSync(srcPath)) {
        output.error(`Source file not found: ${srcPath}`);
        process.exitCode = 1;
        return;
      }

      const raw = readFileSync(srcPath, 'utf8');
      const now = Math.floor(Date.now() / 1000);
      const currentHB = argv.currentHb ?? 285;
      const ctx: MigrationContext = {
        defaultAuthor: argv.author ?? 'migration',
        defaultTimestamp: now,
        timestampForHB: (hb: number) => now - (currentHB - hb) * 15 * 60,
      };

      const parsed: ProjectsBrainDoc = parseProjectsMarkdown(raw, ctx);
      const projects = parsed.projects ?? [];

      if (argv.dryRun) {
        if (output.isJsonMode()) {
          output.json({ status: 'dry-run', docId, parsed });
        } else {
          console.log('');
          console.log(`  Dry-run migration: ${srcPath}`);
          console.log(`  Target doc:        ${docId}`);
          console.log('  ' + '─'.repeat(60));
          console.log(`  Projects parsed:   ${projects.length}`);
          console.log('');
          const stageCounts: Record<string, number> = {};
          for (const p of projects) {
            stageCounts[p.stage] = (stageCounts[p.stage] ?? 0) + 1;
          }
          console.log('  Stage counts:');
          for (const [stage, n] of Object.entries(stageCounts)) {
            console.log(`    ${stage}: ${n}`);
          }
          console.log('');
          console.log('  First 5 projects:');
          for (const p of projects.slice(0, 5)) {
            console.log(`    - ${p.id}  ${p.name.slice(0, 60)}  [${p.stage}]`);
          }
          console.log('');
          console.log('  No changes persisted (--dry-run).');
          console.log('');
        }
        return;
      }

      // Refuse to overwrite an existing doc unless --force. Count only
      // LIVE projects (not tombstoned) when deciding "has content".
      const existing = await openBrainDoc(docId);
      const existingLiveCount = Array.isArray(existing.doc?.projects)
        ? existing.doc.projects.filter((p: any) => p?.removed !== true).length
        : 0;
      if (existingLiveCount > 0 && !argv.force) {
        output.error(
          `Target doc "${docId}" already has ${existingLiveCount} live project(s) at head ${existing.headCid}. ` +
            'Re-run with --force to re-migrate (will merge via Automerge).',
        );
        process.exitCode = 1;
        return;
      }

      const result = await applyBrainChange(docId, (doc: any) => {
        if (!Array.isArray(doc.projects)) doc.projects = [];
        if (argv.force) {
          // Force re-migration: clear existing and re-seed.
          doc.projects.splice(0, doc.projects.length);
        }
        for (const p of projects) doc.projects.push({ ...p });
      });

      if (!argv.noBanner) {
        const banner = DEPRECATED_BANNER(docId, result.headCid);
        if (!raw.includes('DEPRECATED: migrated to')) {
          writeFileSync(srcPath, banner + raw);
        }
      }

      if (output.isJsonMode()) {
        output.json({
          status: 'ok',
          docId,
          headCid: result.headCid,
          projectsMigrated: projects.length,
          sourceFile: srcPath,
          bannerWritten: !argv.noBanner,
        });
      } else {
        console.log('');
        console.log(`  Migration complete: ${srcPath} → ${docId}`);
        console.log(`  New head CID: ${result.headCid}`);
        console.log(`  Projects:     ${projects.length}`);
        if (!argv.noBanner) {
          console.log(`  Banner written to source file.`);
        }
        console.log('');
        console.log(`  Run \`pop brain read --doc ${docId}\` to inspect.`);
        console.log(`  Run \`pop brain snapshot --doc ${docId}\` to produce the .generated.md.`);
        console.log('');
      }
    } catch (err: any) {
      output.error(err.message);
      process.exitCode = 1;
    } finally {
      await stopBrainNode();
    }
  },
};
