/**
 * Task #359 (HB#361): regression guard count test.
 *
 * The snapshot regression guard (HB#301, task #328) used to count H3
 * headers via `/^### /gm` against the rendered markdown. After HB#358
 * (task #357) taught the parser to preserve H3 body content inside
 * lessons (code snippets, embedded markdown), that naive count inflated
 * and the guard reported false mismatches.
 *
 * This test pins the structural-parser-based count so any future change
 * that regresses back to a naive count will fail here.
 *
 * The test is against the parseSharedMarkdown function directly —
 * invoking the CLI command would need daemon + brain home fixtures,
 * and the count logic is the same pure function either way.
 */

import { describe, it, expect } from 'vitest';
import { parseSharedMarkdown } from '../../src/lib/brain-migrate';

const MODERN_BANNER = `# GENERATED BY \`pop brain snapshot\` — DO NOT HAND-EDIT
<!-- Source of truth: Automerge CRDT doc in ~/.pop-agent/brain/helia-blocks -->

# Shared Agent Brain — \`pop.brain.shared\`
*Head CID: \`bafkreitest1234567890\`*

`;

const ctx = {
  defaultAuthor: 'snapshot-regression-guard',
  defaultTimestamp: 0,
};

describe('snapshot regression guard — structural lesson count (task #359)', () => {
  it('counts lessons without being fooled by `### ` inside a code-fenced body', () => {
    // Three lessons total. Lesson #2's body contains TWO fenced `### ` lines
    // as literal code content. The old naive /^### /gm counter would match
    // them (they are at line-start) and report 5, inflating the count and
    // triggering spurious regression-guard refusals. The structural parser
    // correctly tracks code-fence state and returns 3.
    //
    // NOTE: unfenced `### ` at line-start IS structurally a new lesson in
    // the generated.md format. Body H3s must live inside a code fence to
    // be preserved as content. This test only covers the fenced case —
    // the real HB#360-discovered issue was exactly this scenario, where
    // lesson bodies contained code snippets with shell-comment H3 lines.
    const md = MODERN_BANNER + `## Lessons

### First lesson
*author: alice · at: 2026-04-14T10:00:00.000Z · id: first-lesson*

Plain body, no inner H3.

### Second lesson (body contains fenced H3 code)
*author: bob · at: 2026-04-14T11:00:00.000Z · id: second-lesson*

Here is how to run the tool:

\`\`\`bash
### this is a shell comment inside a code fence
pop brain read --doc pop.brain.shared
### another line starting with ### inside the fence
\`\`\`

More body text after the fence.

### Third lesson
*author: carol · at: 2026-04-14T12:00:00.000Z · id: third-lesson*

Third body.
`;

    const parsed = parseSharedMarkdown(md, ctx);
    expect(parsed.lessons).toHaveLength(3);

    // Sanity check: naive /^### /gm regex DOES over-count — this is
    // what the old guard was doing and why it broke after HB#358.
    // Expected: 3 real headers + 2 fenced lines = 5 naive matches.
    const naiveCount = (md.match(/^### /gm) ?? []).length;
    expect(naiveCount).toBe(5);
    expect(naiveCount).toBeGreaterThan(parsed.lessons.length);
  });

  it('counts correctly across a `## Removed lessons` terminator', () => {
    const md = MODERN_BANNER + `## Lessons

### Live one
*author: alice · at: 2026-04-14T10:00:00.000Z · id: live-one*

body one with some \`### \` inline code.

### Live two
*author: bob · at: 2026-04-14T11:00:00.000Z · id: live-two*

body two.

## Removed lessons

*(2 lessons tombstoned)*

- tombstoned-id-1
- tombstoned-id-2
`;

    const parsed = parseSharedMarkdown(md, ctx);
    expect(parsed.lessons).toHaveLength(2);
  });

  it('zero lessons on an empty Lessons section', () => {
    const md = MODERN_BANNER + `## Lessons

*(no lessons yet)*

## Removed lessons
`;

    const parsed = parseSharedMarkdown(md, ctx);
    expect(parsed.lessons).toHaveLength(0);
  });
});
