/**
 * Regression test for task #357 (HB#358): parseSharedMarkdown must handle
 * the modern `.generated.md` format produced by `pop brain snapshot`.
 *
 * Before #357, the parser only understood the hand-written shared.md format
 * and matched H2 headers as lesson titles when fed a modern file. Result:
 * `Lessons: 6` against a 59-entry file.
 *
 * After #357, a banner-detected dispatch sends modern files through
 * parseModernGeneratedMd, which scans H3 entries inside the `## Lessons`
 * section and extracts metadata from the `*author: · at: · id: *` line.
 *
 * This test locks in the fix and provides a regression fixture for future
 * format changes.
 */

import { describe, it, expect } from 'vitest';
import { parseSharedMarkdown, type MigrationContext } from '../../src/lib/brain-migrate';

const ctx: MigrationContext = {
  defaultAuthor: 'test-runner',
  defaultTimestamp: 1_700_000_000,
};

const MODERN_BANNER = `# GENERATED BY \`pop brain snapshot\` — DO NOT HAND-EDIT
<!-- Source of truth: Automerge CRDT doc in ~/.pop-agent/brain/helia-blocks -->
<!-- Edits to this file will be overwritten on the next \`pop brain snapshot\` run. -->

# Shared Agent Brain — \`pop.brain.shared\`
*Head CID: \`bafkreitestcidfixture12345\`*

`;

describe('parseSharedMarkdown — modern generated.md format (task #357)', () => {
  it('parses a minimal single-lesson modern doc', () => {
    const raw = MODERN_BANNER + `## Lessons

### First lesson
*author: alice · at: 2026-04-14T10:00:00.000Z · id: first-lesson*

Body of the first lesson. Plain text.

`;
    const parsed = parseSharedMarkdown(raw, ctx);
    expect(parsed.rules).toHaveLength(0);
    expect(parsed.lessons).toHaveLength(1);
    const l = parsed.lessons[0];
    expect(l.id).toBe('first-lesson');
    expect(l.title).toBe('First lesson');
    expect(l.author).toBe('alice');
    expect(l.body).toBe('Body of the first lesson. Plain text.');
    expect(l.timestamp).toBe(Date.parse('2026-04-14T10:00:00.000Z') / 1000);
  });

  it('parses multiple lessons separated by --- rules', () => {
    const raw = MODERN_BANNER + `## Lessons

### Lesson one
*author: alice · at: 2026-04-14T10:00:00.000Z · id: lesson-one*

Body one.

---

### Lesson two
*author: bob · at: 2026-04-14T11:00:00.000Z · id: lesson-two*

Body two.
`;
    const parsed = parseSharedMarkdown(raw, ctx);
    expect(parsed.lessons).toHaveLength(2);
    expect(parsed.lessons[0].id).toBe('lesson-one');
    expect(parsed.lessons[1].id).toBe('lesson-two');
    // Trailing --- should be stripped from body one.
    expect(parsed.lessons[0].body).toBe('Body one.');
    expect(parsed.lessons[1].body).toBe('Body two.');
  });

  it('treats H2 subheaders inside a lesson body as content, not terminators', () => {
    const raw = MODERN_BANNER + `## Lessons

### Retro-style lesson
*author: alice · at: 2026-04-14T10:00:00.000Z · id: retro-lesson*

This is a lesson that contains markdown H2 subheaders.

## What worked

- Thing one
- Thing two

## What didn't work

- Thing three

---

### Next lesson
*author: bob · at: 2026-04-14T11:00:00.000Z · id: next-lesson*

Body of next lesson.
`;
    const parsed = parseSharedMarkdown(raw, ctx);
    expect(parsed.lessons).toHaveLength(2);
    expect(parsed.lessons[0].id).toBe('retro-lesson');
    // The H2 subheaders MUST be preserved in the body, not split into separate lessons.
    expect(parsed.lessons[0].body).toContain('## What worked');
    expect(parsed.lessons[0].body).toContain('## What didn\'t work');
    expect(parsed.lessons[0].body).toContain('Thing one');
    expect(parsed.lessons[1].id).toBe('next-lesson');
  });

  it('terminates lessons section on ## Removed lessons header', () => {
    const raw = MODERN_BANNER + `## Lessons

### Live lesson
*author: alice · at: 2026-04-14T10:00:00.000Z · id: live-lesson*

This is live.

## Removed lessons

*(1 lesson tombstoned)*

- tombstoned-id

## Other fields
`;
    const parsed = parseSharedMarkdown(raw, ctx);
    expect(parsed.lessons).toHaveLength(1);
    expect(parsed.lessons[0].id).toBe('live-lesson');
    expect(parsed.lessons[0].body).toBe('This is live.');
    // "Removed lessons" content must NOT appear in any parsed lesson body.
    expect(parsed.lessons[0].body).not.toContain('tombstoned-id');
  });

  it('preserves code fences inside lesson body', () => {
    const raw = MODERN_BANNER + `## Lessons

### Code fence lesson
*author: alice · at: 2026-04-14T10:00:00.000Z · id: code-fence*

Run this:

\`\`\`bash
### this is inside a code fence
pop brain read --doc pop.brain.shared
\`\`\`

More body after the fence.
`;
    const parsed = parseSharedMarkdown(raw, ctx);
    expect(parsed.lessons).toHaveLength(1);
    // The ### inside the code fence must NOT start a new lesson.
    expect(parsed.lessons[0].body).toContain('### this is inside a code fence');
  });

  it('handles missing metadata line gracefully', () => {
    const raw = MODERN_BANNER + `## Lessons

### Lesson without metadata

Just a title and body, no author/at/id line.
`;
    const parsed = parseSharedMarkdown(raw, ctx);
    expect(parsed.lessons).toHaveLength(1);
    const l = parsed.lessons[0];
    expect(l.title).toBe('Lesson without metadata');
    // id falls back to slugified title.
    expect(l.id).toBe('lesson-without-metadata');
    // author falls back to ctx.defaultAuthor.
    expect(l.author).toBe('test-runner');
    // timestamp falls back to ctx.defaultTimestamp.
    expect(l.timestamp).toBe(1_700_000_000);
    expect(l.body).toContain('Just a title and body');
  });

  it('returns empty when no ## Lessons header exists', () => {
    const raw = MODERN_BANNER + `\n*(no lessons yet)*\n`;
    const parsed = parseSharedMarkdown(raw, ctx);
    expect(parsed.rules).toHaveLength(0);
    expect(parsed.lessons).toHaveLength(0);
  });

  it('legacy path still works for hand-written shared.md', () => {
    // No modern banner → legacy H2 scanner applies.
    const raw = `# Shared

## Rule one

Short policy item.

## Long lesson (HB#100, alice)

${'x'.repeat(250)}
`;
    const parsed = parseSharedMarkdown(raw, ctx);
    // Short H2 body → rule. Long H2 body → lesson.
    expect(parsed.rules.length + parsed.lessons.length).toBe(2);
    // Find the long lesson.
    const longLesson = parsed.lessons.find(l => l.title?.includes('Long lesson'));
    expect(longLesson).toBeDefined();
    // HB#100 tag should have been extracted → author from tag.
    expect(longLesson!.author).toBe('alice');
  });
});
